### ISSUE TITLE
Weird characters displayed in the application GUI

### ISSUE THREAD

**Issue by jan-slegr** [imodeljs/simple-viewer-app#1]
Hi,

when simple-viewer-app is opened, some captions are displayed using weird / incorrect characters:

![simple-viewer-application](https://user-images.githubusercontent.com/8292864/47898632-f869f180-de76-11e8-8c42-de802fd6c7e8.jpg)

Used configuration:

* Windows 10 version 1709
* National settings: Czech
* Node.js version: 8.12.0

Not critical issue, unofrtunatelly my current knowledge of Node.js / Electron / TypeScript is not good enough to find the bug and to push a modification.

Regards,

  Jan

**Comment by ColinKerr** [comment]
These are pseudolocalizatized strings that we used for internal development to ensure we have prepared our applications for internationalization.  This should be disabled for the sample applications.

Thanks for the bug report.

**Comment by jan-slegr** [comment]
Hi Colin,

thanks for your explanation 😄 

  Jan
