### ISSUE TITLE
How do I show my imodel files in an offline environment using imodeljs?

### ISSUE THREAD

**Issue by DarrenWen** [imodeljs/simple-viewer-app#15]
I don't want to use the user authorization module provided in the project to access the imodel files published in the cloud. I need to use imodejs to access the imodel files on my own server, but I haven't seen the relevant code instance in the project description. Could you please provide the relevant technical materials?thank you

**Comment by sainiroop** [comment]
Hi @DarrenWen,

iModel.js offers the [snapshot](https://github.com/imodeljs/imodeljs/blob/c0d7022731b516eb5ace248422c283d750d6fa8d/core/backend/src/IModelDb.ts#L207
) iModel which is a static point-in-time representation of a state of an iModel. Snapshot iModels don't require user authentication and are meant for archival or data transfer purposes. You could use them for your case, but we **highly** recommend using the iModelHub for managing your iModels and preserving the integrity of your digital twin.

Initial documentation on snapshot iModels will be added in the next push. I will post a link here when its available.

Thanks,
Roop

**Comment by DarrenWen** [comment]
Hi @sainiroop,
Thank you very much for your reply. I would like to know when the next version will be pushed. Is there any specific plan?

**Comment by calebmshafer** [comment]
@DarrenWen the lastest version was pushed last week ([iModel.js 1.1](https://imodeljs.github.io/iModelJs-docs-output/changehistory/)) and the documentation @sainiroop alluded to is [here](https://imodeljs.github.io/iModelJs-docs-output/learning/backend/accessingimodels/#snapshot-imodels).

We're working on better messaging and a stable regular release cadence that is more transparent and predictable so stay tuned for announcements in the coming weeks...

If you have any issues with the snapshot API or documentation, please open those in the [iModel.js repository](https://github.com/imodeljs/imodeljs/issues).

Thanks!
