### ISSUE TITLE
Electron version of app ending up at chrome-error://chromewebdata

### ISSUE THREAD

**Issue by Nicholas227** [imodeljs/simple-viewer-app#16]
When working on the electron version of the app, signing in redirects me eventually to https://qa-ims.bentley.com/?wtrealm=https%3A%2F%2Fqa-imsoidc.bentley.com%2F&wa=wsignin1.0&wreply=https%3A%2F%2Fqa-imsoidc.bentley.com%2Fsignin-wsfed&wctx=CfDJ8EX5Kg56z6hPiC8QAlcWdnN8ZtFl7paCO2Rt8vfBPVfBLFVPNinqWmua3OXo8swANKXStw4KoXijFTDe9ylzJ7V2ojchZCrKHf_cikOf-xmOaXS9NGtY-hPx9B1IE9y4uB1sf8YDQ28qoKAypfXBjuti0URv0PQRarhEIaCYnETU. From here the app attempts to load an invalid URL, which navigates to chrome-error://chromewebdata, but does not throw an error message. How can I fix this? 
Edit* I've found that even when running as electron, in frontend/api/rpc.ts web app RPC is initialized, not electron. Is this intended behavior? 
To reproduce: 
1. Clone the repository
2. npm install, npm run build, npm run electron
3. Login and travel through the steps with console logging saved until it freezes on a blank IFrame.
![2019-06-05_11-36-07](https://user-images.githubusercontent.com/43426629/58973686-2d7c5080-8786-11e9-9018-8f5b51fa3c1b.png)

**Comment by sainiroop** [comment]
For anyone else facing this issue, a fix is currently underway and will be pushed in the next couple of weeks.
