### ISSUE TITLE
unable to build  iModel mobile backend

### ISSUE THREAD

**Issue by rajgadade** [imodeljs/simple-viewer-app#6]
### unable to build  iModel mobile backend

command used to build backend : 
` "npm run build:mobile-backend"`

ERROR in ./node_modules/opener/lib/opener.js
Module not found: Error: Can't resolve 'child_process' in 'C:\CodeBase\imodeljs\pocs\sv-189\simple-viewer-app\node_modules\opener\lib'
 @ ./node_modules/opener/lib/opener.js 2:19-43
 @ ./node_modules/@openid/appauth/built/node_support/node_request_handler.js
 @ ./node_modules/@openid/appauth/built/node_support/index.js
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/oidc/OidcDeviceClient.js
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/oidc/index.js
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/imodeljs-clients-backend.js
 @ ./node_modules/@bentley/imodeljs-backend/lib/BriefcaseManager.js
 @ ./node_modules/@bentley/imodeljs-backend/lib/imodeljs-backend.js
 @ ./lib/backend/main.js

ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'net' in 'C:\CodeBase\imodeljs\pocs\sv-189\simple-viewer-app\node_modules\forever-agent'
 @ ./node_modules/forever-agent/index.js 6:10-24
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/openid-client/lib/helpers/http_request.js
 @ ./node_modules/openid-client/lib/issuer.js
 @ ./node_modules/openid-client/lib/index.js
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/oidc/OidcBackendClient.js
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/oidc/index.js
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/imodeljs-clients-backend.js
 @ ./node_modules/@bentley/imodeljs-backend/lib/BriefcaseManager.js
 @ ./node_modules/@bentley/imodeljs-backend/lib/imodeljs-backend.js
 @ ./lib/backend/main.js

ERROR in ./node_modules/https-proxy-agent/index.js
Module not found: Error: Can't resolve 'net' in 'C:\CodeBase\imodeljs\pocs\sv-189\simple-viewer-app\node_modules\https-proxy-agent'
 @ ./node_modules/https-proxy-agent/index.js 5:10-24
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/RequestHost.js
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/imodeljs-clients-backend.js
 @ ./node_modules/@bentley/imodeljs-backend/lib/BriefcaseManager.js
 @ ./node_modules/@bentley/imodeljs-backend/lib/imodeljs-backend.js
 @ ./lib/backend/main.js

ERROR in ./node_modules/request/node_modules/tough-cookie/lib/cookie.js
Module not found: Error: Can't resolve 'net' in 'C:\CodeBase\imodeljs\pocs\sv-189\simple-viewer-app\node_modules\request\node_modules\tough-cookie\lib'
 @ ./node_modules/request/node_modules/tough-cookie/lib/cookie.js 32:10-24
 @ ./node_modules/request/lib/cookies.js
 @ ./node_modules/request/index.js
 @ ./node_modules/openid-client/lib/helpers/http_request.js
 @ ./node_modules/openid-client/lib/issuer.js
 @ ./node_modules/openid-client/lib/index.js
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/oidc/OidcBackendClient.js
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/oidc/index.js
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/imodeljs-clients-backend.js
 @ ./node_modules/@bentley/imodeljs-backend/lib/BriefcaseManager.js
 @ ./node_modules/@bentley/imodeljs-backend/lib/imodeljs-backend.js
 @ ./lib/backend/main.js

ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'net' in 'C:\CodeBase\imodeljs\pocs\sv-189\simple-viewer-app\node_modules\tunnel-agent'
 @ ./node_modules/tunnel-agent/index.js 3:10-24
 @ ./node_modules/request/lib/tunnel.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/openid-client/lib/helpers/http_request.js
 @ ./node_modules/openid-client/lib/issuer.js
 @ ./node_modules/openid-client/lib/index.js
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/oidc/OidcBackendClient.js
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/oidc/index.js
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/imodeljs-clients-backend.js
 @ ./node_modules/@bentley/imodeljs-backend/lib/BriefcaseManager.js
 @ ./node_modules/@bentley/imodeljs-backend/lib/imodeljs-backend.js
 @ ./lib/backend/main.js

ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'C:\CodeBase\imodeljs\pocs\sv-189\simple-viewer-app\node_modules\forever-agent'
 @ ./node_modules/forever-agent/index.js 7:10-24
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/openid-client/lib/helpers/http_request.js
 @ ./node_modules/openid-client/lib/issuer.js
 @ ./node_modules/openid-client/lib/index.js
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/oidc/OidcBackendClient.js
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/oidc/index.js
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/imodeljs-clients-backend.js
 @ ./node_modules/@bentley/imodeljs-backend/lib/BriefcaseManager.js
 @ ./node_modules/@bentley/imodeljs-backend/lib/imodeljs-backend.js
 @ ./lib/backend/main.js

ERROR in ./node_modules/https-proxy-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'C:\CodeBase\imodeljs\pocs\sv-189\simple-viewer-app\node_modules\https-proxy-agent'
 @ ./node_modules/https-proxy-agent/index.js 6:10-24
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/RequestHost.js
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/imodeljs-clients-backend.js
 @ ./node_modules/@bentley/imodeljs-backend/lib/BriefcaseManager.js
 @ ./node_modules/@bentley/imodeljs-backend/lib/imodeljs-backend.js
 @ ./lib/backend/main.js

ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'C:\CodeBase\imodeljs\pocs\sv-189\simple-viewer-app\node_modules\tunnel-agent'
 @ ./node_modules/tunnel-agent/index.js 4:10-24
 @ ./node_modules/request/lib/tunnel.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/openid-client/lib/helpers/http_request.js
 @ ./node_modules/openid-client/lib/issuer.js
 @ ./node_modules/openid-client/lib/index.js
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/oidc/OidcBackendClient.js
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/oidc/index.js
 @ ./node_modules/@bentley/imodeljs-clients-backend/lib/imodeljs-clients-backend.js
 @ ./node_modules/@bentley/imodeljs-backend/lib/BriefcaseManager.js
 @ ./node_modules/@bentley/imodeljs-backend/lib/imodeljs-backend.js
 @ ./lib/backend/main.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @bentley/simple-viewer-app@0.0.0 build:mobile-backend: `tsc 1>&2 && webpack --config ./node_modules/@bentley/webpack-tools/mobile/backend.config.js --env.outdir=./lib/mobile --env.entry=./lib/backend/main.js --env.bundlename=main `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @bentley/simple-viewer-app@0.0.0 build:mobile-backend script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!

**Comment by roopsaini** [comment]
Hi @rajgadade , This will not work currently as mobile support is not in general availability yet.
