### ISSUE TITLE
npm ERR! 500 Internal Server Error: event-stream@=3.3.4

### ISSUE THREAD

**Issue by dev-end** [imodeljs/simple-viewer-app#7]
This occurs while npm install. Error can be related to this https://github.com/SharePoint/sp-dev-fx-webparts/issues/708

**Comment by roopsaini** [comment]
@dev-end Let's ensure that you are installing the latest packages. Could you please see if you can reproduce this error with a fresh clone?

**Comment by dev-end** [comment]
@roopsaini  yes i again tried with fresh clone. Still same issues. Can you try at your end?

**Comment by roopsaini** [comment]
@dev-end I was not able to reproduce this issue on a clean VM. There could be a conflict between your globally installed packages, and the ones installed for the sample app.  Couple of things to try: 

`npm uninstall -g event-stream` Will clean any global event-stream package.  Then try npm install again.

`npm ls -g --depth 1` will give you a list of top level packages installed globally. If you could share those, we can investigate any potential conflicts.

**Comment by roopsaini** [comment]
Another thing to check is if you are pointing towards the npm public registry. Run `npm config get registry` 

If don't get: https://registry.npmjs.org/ please set the registry using: 
`npm config set registry https://registry.npmjs.org/`

Try `npm install` again

**Comment by dev-end** [comment]
@roopsaini  it was not pointing to the right registry. Thanks a lott. :-)
