### ISSUE TITLE
Error 400: "unauthorized_client"

### ISSUE THREAD

**Issue by bhec362587** [imodeljs/simple-viewer-app#8]
Hi,
when I try to sign into "simple-viewer-app", the following error will occur:

![image](https://user-images.githubusercontent.com/49505211/56027120-0b4af100-5d48-11e9-9467-30dee970ed60.png)
Invalid scope for client!

registered app:

![image](https://user-images.githubusercontent.com/49505211/56101924-45401100-5f5b-11e9-86bd-814c8998ebf7.png)

registered project:

![image](https://user-images.githubusercontent.com/49505211/56101932-60ab1c00-5f5b-11e9-9738-ad361fbe6d28.png)

configuration.ts-imjs_browser_test_scope(default):

![image](https://user-images.githubusercontent.com/49505211/56101952-8fc18d80-5f5b-11e9-8380-58a48fc16878.png)

Node.js version: 10.15.3
Regards,

He

**Comment by roopsaini** [comment]
Hi @bhec362587, 

I am working with the iModel.js team to investigate this issue. For now, can you please try running the app with the default client id:

> imjs_browser_test_client_id = imodeljs-spa-test-2686

That should work for your local environment.

**Comment by bhec362587** [comment]
Hi @roopsaini,

Yes, it worked! Thanks a lot.
But why did I have the problem with my own client Id?

Regards,
He
