### ISSUE TITLE
click button "Open Sample iModel" have dialog box "Property imjs_test_project does not exists."

### ISSUE THREAD

**Issue by bimmodel** [imodeljs/simple-viewer-app#9]
Your statement 
[https://z5h64q92x9.net/proxy_u/en-ru.ru/https/github.com/imodeljs/simple-viewer-app](https://z5h64q92x9.net/proxy_u/en-ru.ru/https/github.com/imodeljs/simple-viewer-app)
[https://imodeljs.github.io/iModelJs-docs-output/getting-started/](https://imodeljs.github.io/iModelJs-docs-output/getting-started/)
does not have enough data on which file to write "imjs_test_project" 
This is only described in the video [https://www.youtube.com/watch?v=SPyN8w1XEAE](https://www.youtube.com/watch?v=SPyN8w1XEAE)

add a link to it in the statement

did everything as in video but all the same I receive an error: "**Property imjs_test_project does not exists.**"

С:\project\simple-viewer-app>npm install

run 'npm audit fix' to fix them, or 'npm audit' for details

after 
npm run build
npm run start:servers
http://localhost:3000/
click button "Open Sample iModel"
**have dialog box "Property imjs_test_project does not exists."**
![Screenshot100](https://user-images.githubusercontent.com/49679816/56212547-e82f8280-6062-11e9-85ac-ffb9ba9fd224.png)

**Comment by bimmodel** [comment]
Сам нашел в чем проблема
Помогло видео [https://www.youtube.com/watch?v=SPyN8w1XEAE](https://www.youtube.com/watch?v=SPyN8w1XEAE)
В моем файле по умолчанию C:\project\simple-viewer-app\src\common\configuration.ts
Отсутствовали строки для заполнения 
`28 imjs_test_project : "<Name of iProject>", // Set this to the name of the sample project `
`29 imjs_test_imodel: "<Name of iModel>", // Set this to the name of the sample iModel`
After watching the video I wrote them manually and everything worked


Similar lines I have by default in another file: C:\project\simple-viewer-app\src\common\config.json
But filling them did not lead to any effect

**Comment by roopsaini** [comment]
Hi @bimmodel,

In the config.json file, the project and imodel entries are commented out: 

  // "imjs_test_project" : "<Name of Project>", // Set this to the name of the sample project
  // "imjs_test_imodel"  : "<Name of iModel>" // Set this to the name of the sample iModel

You need to uncomment them after you fill them out. 

  "imjs_test_project" : "your-sample-project-name", // Set this to the name of the sample project
  "imjs_test_imodel"  : "your-sample-imodel-name" // Set this to the name of the sample iModel

Hope this helps.

**Comment by bimmodel** [comment]
Hi @roopsaini 
Thank you! 
Helped I forgot to remove symbol of "//" in file: C:\project\simple-viewer-app\src\common\config.json
It would be necessary to write about it in the instructions:
[https://z5h64q92x9.net/proxy_u/en-ru.ru/https/github.com/imodeljs/simple-viewer-app](https://z5h64q92x9.net/proxy_u/en-ru.ru/https/github.com/imodeljs/simple-viewer-app)
[https://imodeljs.github.io/iModelJs-docs-output/getting-started/](https://imodeljs.github.io/iModelJs-docs-output/getting-started/)
